repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: values.schema.json
      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28
    hooks:
      - id: helmlint
  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: 2.7.0
    hooks:
      - id: helm-readme-generator
        pass_filenames: false
        always_run: true
        args: [ --readme=README.md, --values=values.yaml, --schema=values.schema.json ]
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        args: [ -q ]
