name: "Publish chart"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-chart:
    name: "Build chart"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set chart version
      run: |
        VERSION="${GITHUB_REF/refs\/tags\//}"
        VERSION="${VERSION/v/}"
        sed -i "s|^version:.*|version:\ \"${VERSION}\"|g" Chart.yaml
    - name: Set chart name for ghcr.io repo
      run: |
        NAME=$(echo ${{ github.repository }} | rev | cut -d "/" -f 1 | rev)
        sed -i "s|^name:.*|name:\ \"${NAME}\"|g" Chart.yaml
    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0
      with:
        version: "3.15.3"
    - name: Build chart
      run: |
        helm dependency update
        helm package .
    - uses: actions/upload-artifact@v4
      with:
        name: charts
        path: "*.tgz"

  publish-chart-github-oci:
    name: "Publish chart to github OCI"
    runs-on: ubuntu-latest
    needs: build-chart
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: charts
      - name: Helm tool installer
        uses: Azure/setup-helm@v4.2.0
        with:
          version: "3.15.3"
      - name: Login into registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin
      - name: Push to registry
        run: |
          REGISTRY="oci://ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
          helm push "$(find *.tgz)" $REGISTRY

  create-release:
    name: "Create release on GitHub"
    runs-on: ubuntu-latest
    needs: build-chart
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: charts
      - uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
          generate_release_notes: true
          make_latest: true
